format = "$username@$hostname $directory $git_branch$character"

[directory]
style = "bold bright-green"
truncation_length = 3

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
format = "[$branch]($style) "
style = "bold bright-yellow"

[git_status]
format = "[$all_status]($style) "
style = "bold red"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$environment]($style) "
style = "bold yellow"
